apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-tracehub-secrets
  namespace: a1-orchestrator
  labels:
    app: mcp-tracehub
    component: tracing
    environment: production
    cluster: a1
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-secret-store
  target:
    name: mcp-tracehub-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        TRACE_SECRET_KEY: "{{ .traceSecretKey }}"
        JAEGER_AGENT_HOST: "{{ .jaegerAgentHost }}"
        ELASTIC_PASSWORD: "{{ .elasticPassword }}"
  data:
  - secretKey: traceSecretKey
    remoteRef:
      key: a1-orchestrator/mcp-tracehub
      property: trace_secret_key
  - secretKey: jaegerAgentHost
    remoteRef:
      key: a1-orchestrator/mcp-tracehub
      property: jaeger_agent_host
  - secretKey: elasticPassword
    remoteRef:
      key: a1-orchestrator/mcp-tracehub
      property: elastic_password