apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-test
  namespace: auth
  labels:
    app.kubernetes.io/name: keycloak-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak-test
    spec:
      serviceAccountName: keycloak
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "control"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.1
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: password
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_DB
              value: "h2-file"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
          args:
            - start
            - --optimized
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: keycloak-data
          emptyDir: {}
        - name: tmp
          emptyDir: {}