apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secret
  namespace: auth
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: a2-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: keycloak-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .adminPassword }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: keycloak/admin
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-secret
  namespace: auth
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: a2-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: keycloak-postgres-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        postgres-password: "{{ .postgresPassword }}"
        user-password: "{{ .userPassword }}"
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: keycloak/postgres
        property: postgres-password
    - secretKey: userPassword
      remoteRef:
        key: keycloak/postgres
        property: user-password