apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-oidc-clients
  namespace: auth
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: a2-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: keycloak-oidc-clients
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        mcp-auth-client-id: "{{ .mcpAuthClientId }}"
        mcp-auth-client-secret: "{{ .mcpAuthClientSecret }}"
        traefik-client-id: "{{ .traefikClientId }}"
        traefik-client-secret: "{{ .traefikClientSecret }}"
        grafana-client-id: "{{ .grafanaClientId }}"
        grafana-client-secret: "{{ .grafanaClientSecret }}"
  data:
    - secretKey: mcpAuthClientId
      remoteRef:
        key: keycloak/oidc-clients
        property: mcp-auth-client-id
    - secretKey: mcpAuthClientSecret
      remoteRef:
        key: keycloak/oidc-clients
        property: mcp-auth-client-secret
    - secretKey: traefikClientId
      remoteRef:
        key: keycloak/oidc-clients
        property: traefik-client-id
    - secretKey: traefikClientSecret
      remoteRef:
        key: keycloak/oidc-clients
        property: traefik-client-secret
    - secretKey: grafanaClientId
      remoteRef:
        key: keycloak/oidc-clients
        property: grafana-client-id
    - secretKey: grafanaClientSecret
      remoteRef:
        key: keycloak/oidc-clients
        property: grafana-client-secret