apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: a2-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: "21.4.1"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: auth
  values:
    replicas: 2
    
    auth:
      adminUser: admin
      existingSecret: keycloak-admin-secret
      passwordSecretKey: password
    
    postgresql:
      enabled: true
      auth:
        postgresPassword: keycloak-postgres
        database: keycloak
        existingSecret: keycloak-postgres-secret
        secretKeys:
          adminPasswordKey: postgres-password
          userPasswordKey: user-password
      primary:
        persistence:
          enabled: true
          size: 8Gi
          storageClass: "longhorn"
    
    service:
      type: ClusterIP
      ports:
        http: 8080
    
    ingress:
      enabled: false  # We'll create a separate ingress
    
    metrics:
      enabled: true
      service:
        port: 8080
      serviceMonitor:
        enabled: false  # We'll create our own
    
    nodeSelector:
      node-role: "ingress"
      host: "A1"  # Temporarily using A1 until A2 is ready
    
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "control"
        effect: "NoSchedule"
    
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    
    livenessProbe:
      httpGet:
        path: /auth/realms/master
        port: http
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5
    
    readinessProbe:
      httpGet:
        path: /auth/realms/master
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    
    startupProbe:
      httpGet:
        path: /auth/realms/master
        port: http
      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 1
      failureThreshold: 60
    
    extraEnv: |
      - name: KEYCLOAK_STATISTICS
        value: all
      - name: KEYCLOAK_LOGLEVEL
        value: INFO
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: https://auth.a1-server.local/auth
    
    extraVolumes: |
      - name: realm-config
        configMap:
          name: keycloak-realm-config
          optional: true
    
    extraVolumeMounts: |
      - name: realm-config
        mountPath: /opt/jboss/keycloak/imports
        readOnly: true