apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
  namespace: auth
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: a2-stack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak