apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mcp-gateway
  namespace: a1-orchestrator
  labels:
    app.kubernetes.io/name: mcp-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mcp-gateway
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mcp-gateway-keda
  namespace: a1-orchestrator
  labels:
    app.kubernetes.io/name: mcp-gateway
spec:
  scaleTargetRef:
    name: mcp-gateway
  pollingInterval: 30
  cooldownPeriod: 300
  idleReplicaCount: 1
  minReplicaCount: 2
  maxReplicaCount: 8
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local:80
        metricName: http_requests_per_second
        threshold: '25'
        query: sum(rate(http_requests_total{service="mcp-gateway",namespace="a1-orchestrator"}[2m]))
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp-gateway
  namespace: a1-orchestrator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-gateway