apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-orchestrator-api-secrets
  namespace: a1-orchestrator
  labels:
    app: mcp-orchestrator-api
    component: api
    environment: production
    cluster: a1
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-secret-store
  target:
    name: mcp-orchestrator-api-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        API_SECRET_KEY: "{{ .apiSecretKey }}"
        DATABASE_URL: "{{ .databaseUrl }}"
        JWT_SECRET: "{{ .jwtSecret }}"
  data:
  - secretKey: apiSecretKey
    remoteRef:
      key: a1-orchestrator/mcp-orchestrator-api
      property: api_secret_key
  - secretKey: databaseUrl
    remoteRef:
      key: a1-orchestrator/mcp-orchestrator-api
      property: database_url
  - secretKey: jwtSecret
    remoteRef:
      key: a1-orchestrator/mcp-orchestrator-api
      property: jwt_secret