apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mcp-auth
  namespace: auth
  labels:
    app.kubernetes.io/name: mcp-auth
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: a2-stack
spec:
  scaleTargetRef:
    name: mcp-auth
  minReplicaCount: 2
  maxReplicaCount: 20
  pollingInterval: 30
  cooldownPeriod: 120
  idleReplicaCount: 0
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.observability.svc.cluster.local:9090
        metricName: http_requests_per_second
        threshold: '100'
        query: sum(rate(http_requests_total{job="mcp-auth"}[1m]))
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.observability.svc.cluster.local:9090
        metricName: auth_queue_length
        threshold: '50'
        query: avg(auth_queue_length{job="mcp-auth"})
    - type: redis
      metadata:
        address: redis.auth.svc.cluster.local:6379
        listName: auth_queue
        listLength: '10'
        enableTLS: 'false'
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Max