apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp-auth
  namespace: auth
  labels:
    app.kubernetes.io/name: mcp-auth
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: a2-stack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-auth