apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mcp-auth
  namespace: auth
  labels:
    app.kubernetes.io/name: mcp-auth
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: a2-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-auth
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics