apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-config-secrets
  namespace: a1-orchestrator
  labels:
    app: mcp-config
    component: config
    environment: production
    cluster: a1
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-secret-store
  target:
    name: mcp-config-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        CONFIG_SECRET_KEY: "{{ .configSecretKey }}"
        ENCRYPTION_KEY: "{{ .encryptionKey }}"
        REDIS_PASSWORD: "{{ .redisPassword }}"
  data:
  - secretKey: configSecretKey
    remoteRef:
      key: a1-orchestrator/mcp-config
      property: config_secret_key
  - secretKey: encryptionKey
    remoteRef:
      key: a1-orchestrator/mcp-config
      property: encryption_key
  - secretKey: redisPassword
    remoteRef:
      key: a1-orchestrator/mcp-config
      property: redis_password