apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-session-config
  namespace: auth
  labels:
    app.kubernetes.io/name: mcp-session
    app.kubernetes.io/component: session-manager
    app.kubernetes.io/part-of: a2-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: mcp-session-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        redis-url: "{{ .redisUrl }}"
        redis-password: "{{ .redisPassword }}"
        session-secret: "{{ .sessionSecret }}"
        encryption-key: "{{ .encryptionKey }}"
  data:
    - secretKey: redisUrl
      remoteRef:
        key: mcp-session/config
        property: redis-url
    - secretKey: redisPassword
      remoteRef:
        key: mcp-session/config
        property: redis-password
    - secretKey: sessionSecret
      remoteRef:
        key: mcp-session/config
        property: session-secret
    - secretKey: encryptionKey
      remoteRef:
        key: mcp-session/config
        property: encryption-key