apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mcp-session
  namespace: auth
  labels:
    app.kubernetes.io/name: mcp-session
    app.kubernetes.io/component: session-manager
    app.kubernetes.io/part-of: a2-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-session
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics