apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: a1-orchestrator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: "https://vault.company.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "a1-orchestrator"
          serviceAccountRef:
            name: external-secrets-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: a1-orchestrator
  annotations:
    argocd.argoproj.io/sync-wave: "0"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-orchestrator-secrets
  namespace: a1-orchestrator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mcp-orchestrator-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Database credentials
        db_username: "{{ .db_username }}"
        db_password: "{{ .db_password }}"
        db_host: "{{ .db_host }}"
        
        # API keys
        openai_api_key: "{{ .openai_api_key }}"
        anthropic_api_key: "{{ .anthropic_api_key }}"
        
        # mTLS certificates
        tls_cert: "{{ .tls_cert }}"
        tls_key: "{{ .tls_key }}"
        ca_cert: "{{ .ca_cert }}"
        
        # OIDC configuration
        oidc_client_secret: "{{ .oidc_client_secret }}"
        oidc_signing_key: "{{ .oidc_signing_key }}"
  data:
    - secretKey: db_username
      remoteRef:
        key: a1-orchestrator/database
        property: username
    - secretKey: db_password
      remoteRef:
        key: a1-orchestrator/database
        property: password
    - secretKey: db_host
      remoteRef:
        key: a1-orchestrator/database
        property: host
    - secretKey: openai_api_key
      remoteRef:
        key: a1-orchestrator/api-keys
        property: openai
    - secretKey: anthropic_api_key
      remoteRef:
        key: a1-orchestrator/api-keys
        property: anthropic
    - secretKey: tls_cert
      remoteRef:
        key: a1-orchestrator/tls
        property: cert
    - secretKey: tls_key
      remoteRef:
        key: a1-orchestrator/tls
        property: key
    - secretKey: ca_cert
      remoteRef:
        key: a1-orchestrator/tls
        property: ca
    - secretKey: oidc_client_secret
      remoteRef:
        key: a1-orchestrator/oidc
        property: client_secret
    - secretKey: oidc_signing_key
      remoteRef:
        key: a1-orchestrator/oidc
        property: signing_key

---
# Alternative: Kubernetes Secret for development/testing
# Remove this in production and use only ExternalSecret above
apiVersion: v1
kind: Secret
metadata:
  name: mcp-orchestrator-dev-secrets
  namespace: a1-orchestrator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    environment: development
type: Opaque
stringData:
  # Development-only secrets (use External Secrets in production)
  db_username: "orchestrator_user"
  db_password: "dev_password_123"
  db_host: "postgresql.database.svc.cluster.local"
  
  # Dummy API keys for development
  openai_api_key: "sk-dev-key-not-real"
  anthropic_api_key: "anthropic-dev-key-not-real"
  
  # Self-signed certs for development mTLS
  tls_cert: |
    -----BEGIN CERTIFICATE-----
    MIIBkTCB+wIJAL7/... (development cert)
    -----END CERTIFICATE-----
  tls_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkq... (development key)
    -----END PRIVATE KEY-----
  ca_cert: |
    -----BEGIN CERTIFICATE-----
    MIIBkTCB+wIJAL7/... (development CA)
    -----END CERTIFICATE-----
  
  # OIDC development secrets
  oidc_client_secret: "dev_oidc_secret_123"
  oidc_signing_key: "dev_signing_key_456"