apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-app
    app.kubernetes.io/component: argocd
    app.kubernetes.io/part-of: platform
spec:
  project: default
  source:
    repoURL: https://github.com/devopsengineernovember-gif/k3s-ai-platform.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /status
    - /metadata/labels
    - /metadata/annotations