apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-identity-map-config
  namespace: auth
  labels:
    app.kubernetes.io/name: mcp-identity-map
    app.kubernetes.io/component: identity-mapper
    app.kubernetes.io/part-of: a2-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: mcp-identity-map-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ldap-url: "{{ .ldapUrl }}"
        ldap-bind-dn: "{{ .ldapBindDn }}"
        ldap-bind-password: "{{ .ldapBindPassword }}"
        ldap-base-dn: "{{ .ldapBaseDn }}"
        cache-ttl: "{{ .cacheTtl }}"
  data:
    - secretKey: ldapUrl
      remoteRef:
        key: mcp-identity-map/config
        property: ldap-url
    - secretKey: ldapBindDn
      remoteRef:
        key: mcp-identity-map/config
        property: ldap-bind-dn
    - secretKey: ldapBindPassword
      remoteRef:
        key: mcp-identity-map/config
        property: ldap-bind-password
    - secretKey: ldapBaseDn
      remoteRef:
        key: mcp-identity-map/config
        property: ldap-base-dn
    - secretKey: cacheTtl
      remoteRef:
        key: mcp-identity-map/config
        property: cache-ttl