apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp-identity-map
  namespace: auth
  labels:
    app.kubernetes.io/name: mcp-identity-map
    app.kubernetes.io/component: identity-mapper
    app.kubernetes.io/part-of: a2-stack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-identity-map