#!/bin/bash
set -e

echo "A2 Node Recovery Guide"
echo "====================="
echo ""
echo "The A2 node (173.36.95.187) is currently NotReady. To bring it back online:"
echo ""
echo "1. SSH to A2 node:"
echo "   ssh cisco@173.36.95.187"
echo ""
echo "2. Check system status:"
echo "   sudo systemctl status k3s-agent"
echo "   sudo journalctl -u k3s-agent -f"
echo ""
echo "3. Common fixes:"
echo "   # Restart k3s agent"
echo "   sudo systemctl restart k3s-agent"
echo ""
echo "   # Check network connectivity to A1"
echo "   ping 173.36.95.18"
echo ""
echo "   # Check disk space"
echo "   df -h"
echo ""
echo "   # Check if kubelet is running"
echo "   sudo systemctl status kubelet"
echo ""
echo "4. If node stays NotReady, check node conditions:"
echo "   kubectl describe node a2"
echo ""
echo "5. After A2 is Ready, update deployments to use A2:"
echo "   kubectl patch deployment traefik -n ingress -p='{\"spec\":{\"template\":{\"spec\":{\"nodeSelector\":{\"host\":\"A2\"},\"tolerations\":[{\"key\":\"dedicated\",\"value\":\"edge\",\"effect\":\"NoSchedule\"}]}}}}'"
echo "   kubectl patch deployment mcp-edge -n ingress -p='{\"spec\":{\"template\":{\"spec\":{\"nodeSelector\":{\"host\":\"A2\"},\"tolerations\":[{\"key\":\"dedicated\",\"value\":\"edge\",\"effect\":\"NoSchedule\"}]}}}}'"
echo ""
echo "Current A2 Node Status:"
kubectl describe node a2 | grep -E "(Ready|NotReady|Conditions|Addresses)" || echo "Node not found or unreachable"