#!/bin/bash
set -e

echo "A2 Authentication Flow Test Plan"
echo "================================"
echo ""
echo "Prerequisites:"
echo "- A2 node should be Ready"
echo "- Actual service containers deployed (not nginx placeholders)"
echo "- External DNS or /etc/hosts configured"
echo ""
echo "Test Sequence:"
echo ""
echo "1. Verify Traefik is responding:"
echo "   curl -I http://auth.a1-server.local:30080/"
echo "   Expected: HTTP redirect or Traefik response"
echo ""
echo "2. Check Keycloak health:"
echo "   curl http://auth.a1-server.local:30080/auth/realms/master"
echo "   Expected: JSON realm configuration"
echo ""
echo "3. Access Keycloak Admin Console:"
echo "   URL: http://auth.a1-server.local:30080/auth/admin/"
echo "   Credentials: admin / [password from setup-secrets.sh output]"
echo ""
echo "4. Test Forward Auth Middleware:"
echo "   curl -H \"Host: a1-server.local\" http://173.36.95.18:30080/protected"
echo "   Expected: Redirect to Keycloak login"
echo ""
echo "5. Test MCP Services:"
echo "   # Direct service health checks"
echo "   kubectl port-forward -n auth svc/mcp-auth 8080:8080 &"
echo "   curl http://localhost:8080/health"
echo "   Expected: {\"status\": \"ok\"}"
echo ""
echo "6. End-to-End Auth Flow:"
echo "   a. Browse to http://a1-server.local:30080/protected"
echo "   b. Should redirect to Keycloak: http://auth.a1-server.local:30080/auth/..."
echo "   c. Login with admin credentials"
echo "   d. Should redirect back with auth headers"
echo ""
echo "Current Status Check:"
echo "===================="
echo ""
echo "Checking current service status..."
echo ""

# Check if any services are running
echo "Traefik pods:"
kubectl get pods -n ingress -l app.kubernetes.io/name=traefik --no-headers 2>/dev/null || echo "No Traefik pods found"
echo ""

echo "Keycloak pods:"
kubectl get pods -n auth -l app.kubernetes.io/name=keycloak --no-headers 2>/dev/null || echo "No Keycloak pods found"
echo ""

echo "MCP service pods:"
kubectl get pods -n auth -l app.kubernetes.io/part-of=a2-stack --no-headers 2>/dev/null || echo "No MCP pods found"
echo ""

echo "Service endpoints:"
kubectl get svc -n ingress traefik -o jsonpath='{.spec.type}: {.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].port} (NodePort: {.spec.ports[0].nodePort})' 2>/dev/null || echo "Traefik service not found"
echo ""

echo "External access URLs:"
NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
HTTP_PORT=$(kubectl get svc traefik -n ingress -o jsonpath='{.spec.ports[?(@.name=="web")].nodePort}' 2>/dev/null || echo "N/A")
echo "- Traefik HTTP: http://$NODE_IP:$HTTP_PORT/"
echo "- Keycloak: http://auth.a1-server.local:$HTTP_PORT/auth/"
echo "- Admin Console: http://auth.a1-server.local:$HTTP_PORT/auth/admin/"